services:
  WEM\PortfolioBundle\Controller\ApiController:
    alias: 'wem_portfolio.controller.api_controller'
    public: true

  wem_portfolio.controller.api_controller:
    class: WEM\PortfolioBundle\Controller\ApiController
    arguments:
      $framework: '@contao.framework'
    public: true
    tags: [ 'controller.service_arguments' ]
