services:
  _defaults:
    autowire: true
    autoconfigure: true
  WEM\PortfolioBundle\:
    resource: '../../../src/'
    exclude:
      - '../../../src/DependencyInjection/'
      - '../../../src/Config/'
      - '../../../src/Resources/'
      - '../../../src/Model/'
      - '../../../src/Module/'
      - '../../../src/Migrations/'
  WEM\PortfolioBundle\Controller\ApiController:
    alias: 'wem_portfolio.controller.api_controller'
    public: true

  wem_portfolio.controller.api_controller:
    class: WEM\PortfolioBundle\Controller\ApiController
    public: true
    tags: [ 'controller.service_arguments' ]