services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  WEM\PortfolioBundle\:
    resource: ../src/
    exclude: ../src/{ContaoManager,DependencyInjection,Wrapper}

  wem.portfolio.service.portfolio:
    class: WEM\PortfolioBundle\Service\PortfolioService
    arguments:
      $contentUrlGenerator: '@contao.routing.content_url_generator'
      $requestStack: '@request_stack'

  WEM\PortfolioBundle\Migration\M20260904_DeleteTranslationsWithNoLocale:
    arguments:
      $connection: '@database_connection'
    tags:
      - { name: contao.migration, priority: 0 }